### ISSUE TITLE
Unified badge styles

### ISSUE THREAD

**Issue by wey-gu** [stevending1st/it-technology-podcast#4]
The badges in readme are not consistent in styles now.

**Comment by wey-gu** [comment]
fixed in https://github.com/stevending1st/it-technology-podcast/pull/9 and it should look like this now:

<img width="447" alt="Screen Shot 2022-09-13 at 10 04 09 AM" src="https://user-images.githubusercontent.com/1651790/189791243-79456017-956e-4502-8d75-8d8911c89bb1.png">

**Comment by stevending1st** [comment]
> fixed in #9 and it should look like this now:

Thank you for your issue and PR. But I don not think that is a problem.
If you think that should be fixed, I may approve PR after.
The different in order to better highlight the number of stars.
